apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- prefix-param.yaml
replacements:
- source:
    kind: ConfigMap
    name: cluster-param
    fieldPath: data.CLUSTER_ENVIRONMENT
  targets:
  - select:
      name: prefix-param
      kind: ConfigMap
    fieldPaths:
    - data.CLUSTER_SPECIFIC_PREFIX
    options:
      delimiter: '-'
      index: 0
- source:
    kind: ConfigMap
    name: cluster-param
    fieldPath: data.CLUSTER_NAME
  targets:
  - select:
      name: prefix-param
      kind: ConfigMap
    fieldPaths:
    - data.CLUSTER_SPECIFIC_PREFIX
    options:
      delimiter: '-'
      index: 1
- source:
    kind: ConfigMap
    name: prefix-param
    fieldPath: data.CLUSTER_SPECIFIC_PREFIX
  targets:
  - select:
      name: simple-ingress
      kind: Ingress
    fieldPaths:
    - spec.rules.0.host
    options:
      delimiter: '.'
      index: 0
