apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: 01-
resources:
- ../00_base

## Edit for "Author" Cluster only.
configMapGenerator:
- name: cluster-param
  behavior: merge
  literals:
  - CLUSTER_NAME=Author
