apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-ingress
spec:
  rules:
  - host: sites.example.com
    http:
      paths:
      - backend:
          service:
            name: service1
            port:
              number: 4200
