apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../00_base

## Edit for "production" environments only.
images:
- name: nginx
  newTag: 1.21.1
configMapGenerator:
- name: cluster-param
  behavior: merge
  literals:
  - ENVIRONMENT=production
