apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pod.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: Pod
      metadata:
        name: myapp-pod
      spec:
        containers:
        - name: myapp-container
          resources:
            limits:
              memory: "200Mi"
              cpu: "0.5"
            requests:
              memory: "20Mi"
              cpu: "0.2"
