apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    ENV_VAR: any_value
spec:
  containers:
  - name: myapp-container
    image: nginx
    ports:
    - name: http
      containerPort: 80
