apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../00_base

## Edit for "stage" environments only.
configMapGenerator:
- name: cluster-param
  behavior: merge
  literals:
  - ENVIRONMENT=stage
