apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../00_base

## Edit for "dev" environments only.
images:
- name: nginx
  newTag: latest
configMapGenerator:
- name: cluster-param
  behavior: merge
  literals:
  - ENVIRONMENT=dev
